name: Pull request continuous integration
on:
  pull_request:
    branches:
      - master
jobs:
  setup_lint_build_test:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm i

      - name: Lint source code
        run: npm run lint

      - name: Run build task
        run: npm run build

